import { prisma } from '@/lib/prisma';
import { OpenAIEmbeddingProvider } from './providers/openai';
import { getPriorArtEmbeddingText, getInventionEmbeddingText } from './normalization';
import { EmbeddingProvider, EmbeddingResult } from './types';

/**
 * Active Embedding Provider Singleton
 */
let activeEmbeddingProvider: EmbeddingProvider = new OpenAIEmbeddingProvider();

export function getEmbeddingProvider(): EmbeddingProvider {
  return activeEmbeddingProvider;
}

export function setEmbeddingProvider(provider: EmbeddingProvider) {
  activeEmbeddingProvider = provider;
}

/**
 * Model Consistency & Fail-Safe Guard (Requirement 5):
 * Ensures vectors generated by different models or dimensions are never mixed or compared.
 */
export function validateModelConsistency(
  storedModel?: string | null,
  storedDim?: number | null
): { valid: boolean; reason?: string } {
  const provider = getEmbeddingProvider();

  if (!storedModel) {
    return { valid: false, reason: 'Missing embedding model metadata.' };
  }

  if (!storedDim) {
    return { valid: false, reason: 'Missing embedding dimension metadata.' };
  }

  if (storedModel !== provider.model) {
    return {
      valid: false,
      reason: `Embedding model mismatch: Record used '${storedModel}', active provider uses '${provider.model}'.`,
    };
  }

  if (storedDim !== provider.dimensions) {
    return {
      valid: false,
      reason: `Embedding dimension mismatch: Record used ${storedDim}, active provider expects ${provider.dimensions}.`,
    };
  }

  return { valid: true };
}

/**
 * Generates and persists embedding for a PriorArtDocument record in PostgreSQL.
 */
export async function embedAndStorePriorArtDoc(docId: string): Promise<EmbeddingResult> {
  const doc = await prisma.priorArtDocument.findUnique({
    where: { id: docId },
  });

  if (!doc) {
    throw new Error(`PriorArtDocument not found for ID: ${docId}`);
  }

  const normalizedText = getPriorArtEmbeddingText(doc);
  const provider = getEmbeddingProvider();
  const result = await provider.embedText(normalizedText);

  // Validate output vector dimensions before DB update
  if (result.dimensions !== provider.dimensions || result.vector.length !== provider.dimensions) {
    throw new Error(
      `Fail-Safe Error: Vector dimension ${result.vector.length} does not match provider expectation ${provider.dimensions}.`
    );
  }

  // Format vector string for pgvector DDL [x, y, z...]
  const vectorStr = `[${result.vector.join(',')}]`;

  await prisma.$executeRawUnsafe(
    `UPDATE "prior_art_documents" 
     SET "embedding" = $1::vector, 
         "embeddingModel" = $2, 
         "embeddingDim" = $3, 
         "updatedAt" = CURRENT_TIMESTAMP 
     WHERE "id" = $4`,
    vectorStr,
    result.model,
    result.dimensions,
    docId
  );

  return result;
}

/**
 * Generates and persists embedding for an Invention record in PostgreSQL.
 */
export async function embedAndStoreInvention(inventionId: string): Promise<EmbeddingResult> {
  const invention = await prisma.invention.findUnique({
    where: { id: inventionId },
  });

  if (!invention) {
    throw new Error(`Invention not found for ID: ${inventionId}`);
  }

  const normalizedText = getInventionEmbeddingText(invention);
  const provider = getEmbeddingProvider();
  const result = await provider.embedText(normalizedText);

  if (result.dimensions !== provider.dimensions || result.vector.length !== provider.dimensions) {
    throw new Error(
      `Fail-Safe Error: Vector dimension ${result.vector.length} does not match provider expectation ${provider.dimensions}.`
    );
  }

  const vectorStr = `[${result.vector.join(',')}]`;

  await prisma.$executeRawUnsafe(
    `UPDATE "inventions" 
     SET "embedding" = $1::vector, 
         "embeddingModel" = $2, 
         "embeddingDim" = $3, 
         "updatedAt" = CURRENT_TIMESTAMP 
     WHERE "id" = $4`,
    vectorStr,
    result.model,
    result.dimensions,
    inventionId
  );

  return result;
}

/**
 * Performs Cosine Distance Vector Search against PriorArtDocument embedding index.
 * Strictly filters by active embedding model and dimension.
 */
export async function searchPriorArtByVector(
  queryVector: number[],
  limit = 5
): Promise<Array<{ id: string; publicationNumber: string; title: string; distance: number }>> {
  const provider = getEmbeddingProvider();

  if (queryVector.length !== provider.dimensions) {
    throw new Error(
      `Search Guard Error: Query vector dimension (${queryVector.length}) does not match active provider (${provider.dimensions}).`
    );
  }

  const vectorStr = `[${queryVector.join(',')}]`;

  // Filter strictly by matching embeddingModel and embeddingDim
  const results: any = await prisma.$queryRawUnsafe(
    `SELECT "id", "publicationNumber", "title", ("embedding" <=> $1::vector) AS distance 
     FROM "prior_art_documents" 
     WHERE "embeddingModel" = $2 
       AND "embeddingDim" = $3 
       AND "embedding" IS NOT NULL 
     ORDER BY distance ASC 
     LIMIT $4`,
    vectorStr,
    provider.model,
    provider.dimensions,
    limit
  );

  return results;
}
